### ISSUE TITLE
Deploys and where can I deploy Not working with Slack

### ISSUE THREAD

**Issue by kfalconer** [atmos/hubot-deploy#104]
`hubot-deploy v0.13.10/hubot v2.18.0/node v5.6.0`

Similar to [comment](https://github.com/atmos/hubot-deploy/issues/86#issuecomment-168681893) from issue #86 The commands `deploys` and `where can I deploy` do not work for slack.

**Comment by atmos** [comment]
@kfalconer I'm working on backporting a lot of the stuff that I've been doing at work in hipchat to work in my personal slack chat. I assume you've set your tokens and hubot can identify who you are on GitHub?

**Comment by atmos** [comment]
So I got this mostly working in my personal slack tonight and noticed that I moved the default response for  "hubot deploys hubot" got moved to an event emission a few releases back.

If you take a look at [this example](https://github.com/atmos/hubot-deploy/blob/master/docs/examples/hipchat.coffee#L35-L36) you should be able to wire it up pretty easily. The "where can I deploy" behavior is [here](https://github.com/atmos/hubot-deploy/blob/master/docs/examples/hipchat.coffee#L43-L44).

Now that I have everything mostly working I can hopefully figure out how to take advantage of some of the rich text formatting stuff available in slack.

**Comment by atmos** [comment]
Closing in favor of #86

**Comment by kfalconer** [comment]
@atmos Here is an example based on hipchat https://gist.github.com/kfalconer/f09a15661b0c4e2b74e7

**Comment by atmos** [comment]
@kfalconer Did you mean a slack example?

**Comment by kfalconer** [comment]
Yes, a slack example based on the existing hipchat example.

**Comment by atmos** [comment]
Working for you now though?

**Comment by kfalconer** [comment]
Yes, the linked example works for me.

**Comment by atmos** [comment]
Cool, I'll drop it in the repo as an example. Thanks.
