### ISSUE TITLE
Token verifier error: `SyntaxError: Unexpected token <` 

### ISSUE THREAD

**Issue by khirakawa** [atmos/hubot-deploy#105]
When running `deploy-token:set:github` against GitHub enterprise, it fails with the message: `Your GitHub token is invalid, verify that it has 'repo' scope.`.  This seems to be caused by [this line](https://github.com/atmos/hubot-deploy/blob/master/src/models/verifiers.coffee#L18), where the `err` is `SyntaxError: Unexpected token <`.  

Upon further inspection, it looks like the problem is fixed if the `hostname` value on [this line](https://github.com/atmos/hubot-deploy/blob/master/src/models/verifiers.coffee#L15) is `github.myorg.com/api/v3` rather than just the hostname, `github.myorg.com`.

Should we change the `hostname` value to be `@config.hostname + @config.path()` instead?

**Comment by atmos** [comment]
We probably should. Can you make a patch for this?
