### ISSUE TITLE
 Unexpected token <

### ISSUE THREAD

**Issue by OKNoah** [atmos/hubot-deploy#39]
I get this response from hubby when I try deploy: ` Unexpected token <`

Here is the `apps.json`:

	{
			"hubot": {
					"provider": "capistrano",
					"repository": "USER/APP-REPO-BOT",
					"environments": [
							"production"
					]
			},
			"MY-APP-NAME": {
					"provider": "capistrano",
					"repository": "USER/APP-REPO",
					"environments": [
							"production",
							"staging"
					]
			}
	}

**Comment by atmos** [comment]
Are you sure your tokens are right? My guess is a malformed response we should be handling.

**Comment by OKNoah** [comment]
I destroyed and created a new token, but no joy. You mean personal access tokens created through [/settings/applications](https://github.com/settings/applications), right? And given to hubot through the `deploy-key:set` command?

**Comment by parkr** [comment]
@OKNoah This error is usually because you've gotten some HTML back. Is there a way for you to inspect the response?

**Comment by OKNoah** [comment]
@parkr With instructions maybe. I am new to hubot.

**Comment by atmos** [comment]
@OKNoah Do you have a stacktrace or anything that would help me identify where it's blowing up on you?
