### ISSUE TITLE
Feedback on deploy status

### ISSUE THREAD

**Issue by a-warner** [atmos/hubot-deploy#41]
Sorry if there is obvious documentation that I'm missing on this, but I can't seem to get hubot to print out the message indicated in the docs, even when a deployment is successful (and I can see the successful deployment status in the github api):

![](https://dl.dropbox.com/u/430341/photos/2015-04-22_0919.png)

I've also scanned the code and I don't see where this part is implemented. Am I missing something?

**Comment by atmos** [comment]
You need a [heaven](https://github.com/atmos/heaven) install or something that sends deployment status notifications to your chat server. Slack told me they'd do it a while back and never did.

**Comment by a-warner** [comment]
@atmos ah so there is no direct hubot functionality to wait for deployment status updates, the goal is to have something else send a notification to chat?

I might try to whip up a PR to have hubot poll for updates to the deployment status, or maybe register for webhooks if GH supports deploy-related notifs.

**Comment by atmos** [comment]
We could probably do it w/ organization webhooks pretty easily.

**Comment by atmos** [comment]
I think I already have the hubot http adapter running due to slack integration. I think that might be the easiest and possibly best way to do all of this.

**Comment by a-warner** [comment]
@atmos so basically that flow is:

1. hubot registers for webhooks on all deployments on a repo
1. hubot creates a deployment on github
2. something else (heaven, herokubeta service) deploys somewhere
3. thing from step 3 updates github deployment with the status (e.g. "success")
4. github sends a webhook to hubot
5. hubot reports "success" in chat

seems reasonable! now I just have to figure out how to get `HerokuBeta` to deploy to multiple apps for staging/prod..

**Comment by atmos** [comment]
Check out the docs, https://github.com/atmos/hubot-deploy/blob/master/docs/config-file.md

**Comment by a-warner** [comment]
@atmos yea I saw that hubot-deploy supports multiple environments but it seems like `HerokuBeta` always deploys to the [preconfigured heroku application name](https://github.com/github/github-services/blob/850325f8a7d6a8a37c0373725132b45f2725cd49/lib/services/heroku_beta.rb#L61-L63)? (sorry if I'm missing something)

**Comment by atmos** [comment]
Huh, looks like you're right. I've been using it with heaven for multi-environment support. We should adapt that heroku beta to behave like the aws-codedeploy one. It supports arbitrary envs instead of weird environment name interpolation.

**Comment by a-warner** [comment]
@atmos i'd be happy to make the change to github-services, but there probably isn't an easy way for me to test it, right?

**Comment by atmos** [comment]
Today is my last day as a GitHub employee but I use it a bunch so I'll send them a PR next week.

**Comment by atmos** [comment]
Hey are you still using this? I added some stuff this week that does all of this.

**Comment by a-warner** [comment]
cool! @atmos we're not using it but i might look into switching to it again :)
