### ISSUE TITLE
Allowed Rooms for Slack

### ISSUE THREAD

**Issue by edenvicary** [atmos/hubot-deploy#43]
I've got hubot-deploy working in Slack, except for allowing rooms. I've got it defined like this in the apps.json:

```json
  "abc-web": {
    "provider": "heroku",
    "repository": "cvcnetwork/abc-web",
    "environments": ["staging", "production"],
    "heroku_staging_name": "abc-web-staging",
    "heroku_production_name": "abc-web-production",
    "allowed_rooms": ["abc-next-activity"]
  },
```

But the rooms aren't being limited to the specified room, I also tried specifying a '#' at the start of the name, my only guess is that https://github.com/atmos/hubot-deploy/blob/master/src/scripts/deploy.coffee#L78 doesn't work as well with the Slack API?

**Comment by atmos** [comment]
We should change the logging levels to view these inputs and their outputs. I used this on campfire a while ago but it *should* work on an adapter basis.

**Comment by atmos** [comment]
I think the adapter might be missing the interpretation of what [matching](https://www.twelvesouth.com/product/hirise-apple-watch) means.

**Comment by atmos** [comment]
Was it just misconfigured?

**Comment by edenvicary** [comment]
Yeah it seemed to work without the hash.
