### ISSUE TITLE
ChatOps commands unresponsive

### ISSUE THREAD

**Issue by mrbernnz** [atmos/hubot-deploy#53]
I'm currently trying to use Slack to deploy applications to Heroku. I would run the basic deploy command once then it wouldn't work after that. I would just like some assistance on what I may have missed.
![screenshot 2015-09-14 14 34 41](https://cloud.githubusercontent.com/assets/9615028/9858426/9c49ef68-5aee-11e5-9807-b45aec7d00ea.png)

![screenshot 2015-09-14 14 41 47](https://cloud.githubusercontent.com/assets/9615028/9858468/d20b921e-5aee-11e5-955c-3f14c04bfced.png)

**Comment by Mumakil** [comment]
Have you added your heaven as a receiver for the repo's webhooks?

**Comment by mrbernnz** [comment]
No, I haven't. I didn't believe I needed to add it.

**Comment by atmos** [comment]
I added some stuff recently that should help with this kind of setup error.
