### ISSUE TITLE
Does `auto_merge: true` send a deployment event when a merge is performed?

### ISSUE THREAD

**Issue by willdurand** [atmos/hubot-deploy#54]
Hi @atmos!

On a project configured with `auto_merge` set to `true`, I have an issue when a branch needs a merge: it looks like an event is successfully sent to merge the branch, but it does not deploy and I don't get any feedback. I have to send another event to actually perform the deployment.

Example:

```
willdurand> hubot deploy project/master in production
hubot> willdurand: Auto-merged develop into master on deployment.
```

I checked the GitHub documentation, and all I found is:

> The auto_merge parameter is used to ensure that the requested ref is not behind the repository’s default branch. If the ref is behind the default branch for the repository, we will attempt to merge it for you. If the merge succeeds, the API will return a successful merge commit. If merge conflicts prevent the merge from succeeding, the API will return a failure response.

But, I am not sure about what it exactly means. Isn't it supposed to deploy the code too? Or is sending a new deployment event expected? Thanks!

**Comment by atmos** [comment]
Normally this is used in conjunction with commit statuses so you'd get feedback that the new branch that merged in the default branch was successful or not. At that point you can issue a new deployment request, or use auto deployment base on commit statuses.

**Comment by willdurand** [comment]
I get the feedback on the merge result. What I would have expected is that the deployment would have been performed right after.

**Comment by atmos** [comment]
Yeah, it's difficult to reason about it w/o being able to generalize the required contexts so it was omitted. You'll have to handle this externally in something like hubot or another system.

**Comment by atmos** [comment]
I added the ability to respond to incoming webhook events this week. If we listen for status I think this logic can all be done in hubot.
