### ISSUE TITLE
TokenVerifier does not respect HUBOT_GITHUB_API

### ISSUE THREAD

**Issue by cyc** [atmos/hubot-deploy#60]
Spent a good amount of time wondering why my token worked when set via `HUBOT_GITHUB_TOKEN`, but not when set via `deploy-token:set:github`. It seems like the Octonode client is not being given the API URL: https://github.com/atmos/hubot-deploy/blob/1b0a4af396781e7849bbfb85fe5a3e475c16e2f2/src/models/token_verifier.coffee#L7

**Comment by atmos** [comment]
Hwhoops. I'll see about consolidating all of this since I'm going through it again.
