### ISSUE TITLE
Token Verifier does not actually inspect returned headers

### ISSUE THREAD

**Issue by cyc** [atmos/hubot-deploy#61]
@atmos 

I believe [this line](https://github.com/atmos/hubot-deploy/blob/32da3b7d74e347ae35dc70f0b2d17bc89cddc18b/src/models/token_verifier.coffee#L14) needs to be

```coffee
    @api.get "/user", (err, data, body, headers) ->
```

Or else it will never actually look at the headers returned.

**Comment by jroes** [comment]
@cyc he just fixed this in 0.8.30, released on npm, but actually looks like it's not pushed to GitHub right now.
