### ISSUE TITLE
hubot deploys app/branch in env ignores branch

### ISSUE THREAD

**Issue by cyc** [atmos/hubot-deploy#69]
Seems like this is not a bug, just not implemented yet. Figure I'd add a ticket to track it

**Comment by atmos** [comment]
Yeah, I'm not sure if I want to add this.  Non-master branches tend to be short lived, so I wanted this to reflect the most recent deployments across all branches in an environment.

**Comment by cyc** [comment]
SGTM. May want to simply update the help messages to reflect this. Thanks!
