### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by mcapanema** [atmos/hubot-deploy#72]
Hello,

I am trying to create a deployment on github via hubot-deploy but it is returning 404 for some reason.
The token provided has the right scope as far as I can see according to the hubot-deploy documentation(`repo`, `user`).
Referring to the Github documentation(https://developer.github.com/v3/repos/deployments/#create-a-deployment), seems that all the parameters are present.

```
{"ref":"production","task":"deploy","force":false,"auto_merge":false,"environment":"production","required_contexts":[],"description":"Deploying from hubot-deploy-v0.6.53","payload":{"name":"operational","hosts":"","notify":{"room":"deploy","user":"murilo.capanema","adapter":"slack","message_thread":"unknown"},"config":{"provider":"capistrano","auto_merge":false,"repository":"<my_repository>","environments":["production"],"required_contexts":[]}}}
{ [Error: Not Found]
  message: 'Not Found',
  statusCode: 404,
  headers:
   { server: 'GitHub.com',
     date: 'Tue, 03 Nov 2015 21:04:32 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '77',
     connection: 'close',
     status: '404 Not Found',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4986',
     'x-ratelimit-reset': '1446586559',
     'x-oauth-scopes': 'repo, user',
     'x-accepted-oauth-scopes': '',
     'x-github-media-type': 'github.v3; param=cannonball-preview; format=json',
     'x-xss-protection': '1; mode=block',
     'x-frame-options': 'deny',
     'content-security-policy': 'default-src \'none\'',
     'access-control-allow-credentials': 'true',
     'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'access-control-allow-origin': '*',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-content-type-options': 'nosniff',
     'x-github-request-id': 'BF224904:1AD4:C71F604:56392160' } }
```

There is any extra configuration that I must provide ?

**Comment by atmos** [comment]
The only thing that I could see being wrong is if it's using the wrong API token to submit the deployment. The unfortunate thing is that the API 404s on bad credentials to avoid leaking the existence of private repositories. I'm pretty sure I was using that version successfully for a long time though. I'll think about it some.

**Comment by mcapanema** [comment]
I see.
The problem was really on API token, the token provided on hubot `apps.json` was overwriting the user token and the token provided via env `HUBOT_GITHUB_TOKEN`.
Is this behaviour expected ?

**Comment by mcapanema** [comment]
To solve my problem I just removed the `github_token` from `apps.json` and passed a valid token to hubot via chat.

**Comment by atmos** [comment]
> The problem was really on API token, the token provided on hubot apps.json was overwriting the user token and the token provided via env HUBOT_GITHUB_TOKEN.
> Is this behaviour expected ?

It is. It's intended to allow you to work with both github enterprise and github.com installs simultaneously. I'm going to start logging a sha1 hash of the token for easier debugging like this and other things.
