### ISSUE TITLE
Issues with hubot-vault after upgrading

### ISSUE THREAD

**Issue by torbjornvatn** [atmos/hubot-deploy#86]
I've upgraded from `0.6.56` to `0.12.1`, but I can't make it work.

This is the error message I get, so it seems that `hubot-vault` isn't loaded correctly:

`2015-12-30T13:36:48.411637+00:00 app[web.1]: [Wed Dec 30 2015 13:36:48 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'forUser' of undefined
2015-12-30T13:36:48.411640+00:00 app[web.1]:   at TextListener.callback (/app/node_modules/hubot-deploy/src/scripts/deploy.coffee:95:24)`

**Comment by atmos** [comment]
I ran into this before and tried dropping `hubot-vault` into my `external-scripts.json` but I'm not seeing that in my current, functional, hubot using this. I'll see what I can track down today.

**Comment by atmos** [comment]
@torbjornvatn I'm in the process of updating my slack bot now, but this should work for you.

**Comment by torbjornvatn** [comment]
I upgraded to 0.12.5 and the `deploy` command works as it should.

However it seems that `deploys` and `where can I deploy` has stopped working. I see that `deploy.coffee` was altered to use `robot.emit` in `0.10.0`. Am I supposed to add some custom `robot.on` code like the one in the [hipchat example](https://github.com/atmos/hubot-deploy/blob/master/docs/examples/hipchat.coffee), or is something missing?

**Comment by atmos** [comment]
I need to finish a slack example. Hopefully soon. :snowboarder:

**Comment by atmos** [comment]
So I got this mostly working in my personal slack tonight and noticed that I moved the default response for  "hubot deploys hubot" got moved to an event emission a few releases back.

If you take a look at [this example](https://github.com/atmos/hubot-deploy/blob/master/docs/examples/hipchat.coffee#L35-L36) you should be able to wire it up pretty easily. The "where can I deploy" behavior is [here](https://github.com/atmos/hubot-deploy/blob/master/docs/examples/hipchat.coffee#L43-L44).

Now that I have everything mostly working I can hopefully figure out how to take advantage of some of the rich text formatting stuff available in slack.
