### ISSUE TITLE
Support Github Enterprise

### ISSUE THREAD

**Issue by khirakawa** [atmos/hubot-deploy#91]
Currently, the `GitHubWebHookIpVerifier` hardcodes the acceptable Github IPs to be in the subnet range of `192.30.252.0/22`.  This means that webhooks created in Github Enterprise deployments will fail because of [this method](https://github.com/atmos/hubot-deploy/blob/master/src/models/verifiers.coffee#L28)

Is there a way we can configure this IP?

**Comment by atmos** [comment]
We could probably add an environmental variable to make this easier for enterprise installs. Maybe comma delimited?
